spring:
  datasource:
    url: jdbc:mariadb://192.168.0.17/goodc
#    url: jdbc:mariadb://localhost:3306/boot
    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root
    username: goodc
    password: Goodc1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: C:\Users\aa\Desktop\test2
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: goodcastingofficial@gmail.com
    password: goodc1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret: secret-value
shop:
  goodcast:
    upload:
      path: C:\Users\aa\Desktop\test2